# Generated by Django 4.0.10 on 2023-07-26 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
